[package]
name = "gball"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.11.0"
glutin = "0.28"
winit = "0.26.1"

ordered-float = "2.0"
minvect = "0.1.3"
glow_mesh = "0.1.2"
minimg = "0.1.2"
minirng = "0.1.0"
